### ISSUE TITLE
Desglozar tareas hechas del sprint 2 para facturar cliente

### ISSUE THREAD

**Issue by tomyo** [HA-Team/duit#107]

**Comment by tomyo** [comment]
Hola @LeviTamiozzo!
Te recuerdo esto así le detallo y facturo al cliente. 
Abrazo! Cualquier cosa avisame!

**Comment by LeviTamiozzo** [comment]
@tomyo Buenas! Ya está hecho todo el desglose, chusmealo y avisame porfa cualquier cosa, gracias, Abrazo!
