### ISSUE TITLE
Featured And Similar Sliders [][3]

### ISSUE THREAD

**Issue by LeviTamiozzo** [HA-Team/duit#19]

**Comment by tomyo** [comment]
Las imágenes se siguen viendo estiradas:
![image](https://user-images.githubusercontent.com/708569/79657914-9066b280-81b3-11ea-8482-d9d96bf88b5c.png)

Propongo dejarlas en el aspecto original, y reducir el largo de esas secciones:
![image](https://user-images.githubusercontent.com/708569/79659467-066b1980-81b4-11ea-9305-119cb71a3d91.png)
