### ISSUE TITLE
Prices On Properties Listing Filter

### ISSUE THREAD

**Issue by LeviTamiozzo** [HA-Team/duit#21]

**Comment by tomyo** [comment]
Hola!
El problema sería como resolver el rango de precios cuando el filtro incluye propiedades en pesos y dólares?

**Comment by LeviTamiozzo** [comment]
Así es, se me ocurre podríamos poner un radio button para que el user elija en USD o $ y hacemos la conversión en el back usando alguna API.

**Comment by tomyo** [comment]
Por ahora, lo dejamos como está, hasta que el cliente pida un cambio, pues parece estar conforme con la actual funcionalidad.
