### ISSUE TITLE
Contact a agent in product detail [][4]

### ISSUE THREAD

**Issue by tomyo** [HA-Team/duit#33]
Ubicación del feature:
Donde ahora está el ícono del agente, debajo del producto:
![image](https://user-images.githubusercontent.com/708569/79446017-e124b280-7fdd-11ea-8857-ee8460dcd4c3.png)

Objetivo: 
Convertir la imagen redonda del asesor, en un botón que abre un pequeño modal.
* Usar imagen redonda, "solapada" con la imagen de whatsapp (se adjunta idea del cliente)
   ![image](https://user-images.githubusercontent.com/708569/79446857-3ca37000-7fdf-11ea-8596-5bba04f8e4fb.png) 

El modal incluirá:
```
<foto>  <nombre_asesor>
        <botón mandar email> <botón mandar whatsapp>
```
* Para el botón de mandar email, usar símbolo del sobre (envelope).
* Para el botón de mandar whatsapp, usar símbolo de whtasapp.

Inspirarse en la siguiente propuesta diseño:
![image](https://user-images.githubusercontent.com/708569/79446246-36f95a80-7fde-11ea-866f-15e9b5cb9b26.png)

Notas: La propuesta de diseño mantiene el botón de dezplegar modal arriba del modal, eso, claramente, está mal.
Se deja a criterio del desarrollador cómo y dónde mostrar el modal, o si en lugar de modal, el botón de contactar agente se expande a lo requerido, al tocarse.

**Comment by tomyo** [comment]
Viene muy bien!.
Algunas correcciones:
- [x] Imagen y botón de contactar agente.
  * Fixear alto y ancho y darle `object-fit: cover` (hacer el fix en desktop y mobile si posible)
  ![image](https://user-images.githubusercontent.com/708569/79553196-6b335080-809c-11ea-8a49-71c4ae126f42.png)
  Creo que 60x60px va bien.

  * Encajar de forma mas simétrica el logo de whatsapp
  * Usar X para cerrar modal mas fino (el que reemplaza al ícono de whatsapp cuando se expande)

- [x] Click en a foto debe abrir modal también.

**Comment by tomyo** [comment]
Creo que en la propuesta actual (fijo en el subtítulo del producto), no se nota que es un botón.

Te propongo que lo hagas fixed, abajo a la derecha, tipo el botón de acción de Material design:
![image](https://user-images.githubusercontent.com/708569/79557010-26121d00-80a2-11ea-88f3-8dd590c31ef0.png)

**Comment by LeviTamiozzo** [comment]
Ahí fueron algunas correcciones! Fijate cómo quedó y avisame!

**Comment by tomyo** [comment]
Buenísimo!
Poné el botón simétrico en distancia a los bordes, onda:
![image](https://user-images.githubusercontent.com/708569/79578364-6b484600-80c6-11ea-800a-de7301aac156.png)

**Comment by tomyo** [comment]
Podés implementar el mandar mensaje al teléfono de asesor?

**Comment by tomyo** [comment]
Para el asunto del email: "Consulta por propiedad #id: <título/short description de la propiedad>"

**Comment by LeviTamiozzo** [comment]
> Podés implementar el mandar mensaje al teléfono de asesor?

Esto en teoría ya está implementado, al menos a mí me funciona, te referís al Whatsapp, no?

**Comment by LeviTamiozzo** [comment]
> Buenísimo!
> Poné el botón simétrico en distancia a los bordes, onda:
> ![image](https://user-images.githubusercontent.com/708569/79578364-6b484600-80c6-11ea-800a-de7301aac156.png)

Done!

**Comment by LeviTamiozzo** [comment]
> Para el asunto del email: "Consulta por propiedad #id: <título/short description de la propiedad>"

Done!

**Comment by tomyo** [comment]
- [x] Hacer botón flotante sticky.
  Probé hacer esto y me gustó como queda:
   ![image](https://user-images.githubusercontent.com/708569/79654876-ae7fe300-81b2-11ea-8d27-f0a3ec249c24.png)
  Otra cosa buena de ponerle el sticky como está, es que se frena cuando empezás a ver la sección de las otras propiedades, me parece conceptualmente bien:
![image](https://user-images.githubusercontent.com/708569/79655511-de2eeb00-81b2-11ea-9d56-ba968ebabedb.png)
