### ISSUE TITLE
Mejorar UX de Street View en vista de una propiedad

### ISSUE THREAD

**Issue by LeviTamiozzo** [HA-Team/duit#40]
* Botón para ver el Street View.
  - [ ] Ubicación es un botón (muestra el mapa actual)
  - [ ] Street View <muñequito>: te lleva al street view

**Comment by tomyo** [comment]
Lo ideal seríá que se pueda modificar el widget de google maps y que aparezca la opción en el mapa directamente. Sinó, un botón al lado del título con el logo del street view.

![image](https://user-images.githubusercontent.com/708569/79126005-653d2700-7d9f-11ea-98c2-a939b9a7ff05.png)
