### ISSUE TITLE
Revisar texto sección "Nosotros" [.1]

### ISSUE THREAD

**Issue by LeviTamiozzo** [HA-Team/duit#58]

**Comment by tomyo** [comment]
En Duit contamos con más de 10 años de experiencia en el mercado inmobiliario, somos personas con un mismo sueño, con una misma forma de ver la vida, de superarnos, de dar lo mejor.
Comprendemos la importancia y trascendencia que tiene en la vida de las personas, la compra o alquiler de una vivienda, local comercial o cualquier otro tipo de transacción inmobiliaria. 
Generamos vínculos a largo plazo, y trabajamos enfocados en lograr que el beneficio sea para todos. 
Se trata de identidad, de valores, de una forma de hacer las cosas, y aconsejar, es la única que nos representa.
