### ISSUE TITLE
Implementar scroll suave en los links del home

### ISSUE THREAD

**Issue by tomyo** [HA-Team/duit#80]

**Comment by tomyo** [comment]
No me había dado cuenta que la garcha de angular, al harcordear los hashes, rompe el estandar web de scroll to id por defecto.
Estuve media hora renegando y no logré ni siquiera poder hacer scroll a elementos del dom.

Te delego esta tarea, @LeviTamiozzo, que parece necesitar magia de angular, y no quiero hacer chanchadas.

Probé un poco con esto, sin suerte: https://docs.angularjs.org/api/ng/service/$anchorScroll

Yo personalmente pasé a odiar el manejo de urls de Angularjs.
Además me doy cuenta de que no se mantiene el historial de urls visitadas, osea, no funciona el back del navegador!

**Comment by LeviTamiozzo** [comment]
Buenas! Ya estoy de vuelta!
Jaja, sí, hay que renegar un poco, yo me encargo :)
